steps:
 - task: DownloadPipelineArtifact@2
   inputs:
    artifact: ${{variables.artifact}}
    path: $(build.artifactstagingdirectory)
 - task: AzureWebApp@1
   displayName: 'Azure Web App Deploy: insight-webapp'
   inputs:
    azureSubscription: ${{variables.azureSubscription}}
    appType: ${{variables.apptype}}
    appName: ${{variables.webapp}}
    package: $(build.artifactstagingdirectory)/**/*.zip
